package Tiket;

import Menu.Menu_Utama;
import Server.Koneksi;
import java.io.File;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;

public class Form_Tiket_KA extends javax.swing.JDialog {
    int Vip, Ekonomi, Harga, Beli, Total, Bayar, Kembali;
    
    Tiket tiket;

   
    public Form_Tiket_KA(java.awt. Frame parent, boolean modal) {
        super (parent, modal);
        initComponents ();
        tiket =new Tiket ();
        TableModel modeltiket_ka;
        tabel_tiket_ka.setModel (tiket.modeltiket_ka);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Jurusan = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        rb_Vip = new javax.swing.JRadioButton();
        rb_Ekonomi = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        txt_Harga = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btn_simpan = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_new = new javax.swing.JButton();
        btn_kembali = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_tiket_ka = new javax.swing.JTable();
        btn_print = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_no_kursi = new javax.swing.JTextField();
        txt_nama_penumpang = new javax.swing.JTextField();
        txt_jml_beli = new javax.swing.JTextField();
        txt_uang_bayar = new javax.swing.JTextField();
        txt_total_bayar = new javax.swing.JTextField();
        txt_uang_kembali = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pemesanan Tiket KA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Data Kereta");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Jurusan");

        Jurusan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Purwokerto - Solo", "Purwokerto - Surabaya", "Purwokerto - Semarang", "Purwokerto - Bandung", "Purwokerto - Jember" }));
        Jurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JurusanActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Jenis");

        rb_Vip.setForeground(new java.awt.Color(255, 255, 255));
        rb_Vip.setText("Eksekutif");
        rb_Vip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_VipActionPerformed(evt);
            }
        });

        rb_Ekonomi.setForeground(new java.awt.Color(255, 255, 255));
        rb_Ekonomi.setText("Ekonomi");
        rb_Ekonomi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_EkonomiActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Harga");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("No Kursi");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Jumlah Beli");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Total Harga");

        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        btn_edit.setText("Edit");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        btn_new.setText("Reset");
        btn_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_newActionPerformed(evt);
            }
        });

        btn_kembali.setText("Kembali");
        btn_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kembaliActionPerformed(evt);
            }
        });

        tabel_tiket_ka.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No Kursi", "Nama Penumpang", "Jumlah Beli", "Uang Bayar", "Total Bayar", "Uang Kembali"
            }
        ));
        jScrollPane1.setViewportView(tabel_tiket_ka);

        btn_print.setText("Print");
        btn_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_printActionPerformed(evt);
            }
        });

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Nama Penumpang");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Uang Bayar");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Uang Kembali");

        txt_jml_beli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_jml_beliActionPerformed(evt);
            }
        });
        txt_jml_beli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_jml_beliKeyReleased(evt);
            }
        });

        txt_uang_bayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_uang_bayarKeyReleased(evt);
            }
        });

        txt_total_bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_total_bayarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(btn_simpan))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rb_Vip)
                                    .addComponent(rb_Ekonomi)
                                    .addComponent(txt_Harga, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Jurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(57, 57, 57)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel6)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btn_edit)
                                .addGap(19, 19, 19)
                                .addComponent(btn_hapus)
                                .addGap(19, 19, 19)
                                .addComponent(btn_new)
                                .addGap(17, 17, 17)
                                .addComponent(btn_print)))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_nama_penumpang)
                            .addComponent(txt_jml_beli)
                            .addComponent(txt_uang_bayar)
                            .addComponent(txt_total_bayar)
                            .addComponent(txt_uang_kembali, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                            .addComponent(txt_no_kursi)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btn_kembali)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(Jurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(9, 9, 9)
                                .addComponent(rb_Vip)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rb_Ekonomi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txt_Harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_no_kursi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_nama_penumpang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_jml_beli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_uang_bayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_total_bayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_uang_kembali, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_simpan)
                    .addComponent(btn_edit)
                    .addComponent(btn_hapus)
                    .addComponent(btn_new)
                    .addComponent(btn_print)
                    .addComponent(btn_kembali))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
boolean edit=false;
   
    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // TODO add your handling code here:
                String No_kursi=txt_no_kursi.getText ();
                String Nama_penumpang=txt_nama_penumpang.getText (); 
                String Uang_bayar=txt_uang_bayar.getText();
                String Jumlah_beli=txt_jml_beli.getText();
                String Total_bayar=txt_total_bayar.getText();
                String Uang_kembali=txt_uang_kembali.getText ();
                if (txt_no_kursi.equals("")){
                    
                    
            JOptionPane.showMessageDialog (null, "Data harus diisi"); 
            txt_no_kursi.requestFocus();
        }
        else if(txt_Harga.getText().isEmpty()) {
            JOptionPane.showMessageDialog (null, "Data harus diisi");
            txt_Harga.requestFocus();
        }
        else if(txt_nama_penumpang.getText().isEmpty()) {
            JOptionPane.showMessageDialog (null, "Data harus diisi"); 
            txt_nama_penumpang.requestFocus();
        }
        else if(txt_uang_bayar.getText().isEmpty()) {
            JOptionPane.showMessageDialog (null, "Data harus diisi");
            txt_uang_bayar.requestFocus();
        }
        else if(txt_jml_beli.getText().isEmpty()) {
            JOptionPane.showMessageDialog (null, "Data harus diisi"); 
            txt_jml_beli.requestFocus();
        }
        else if(txt_total_bayar.getText().isEmpty()) {
            JOptionPane.showMessageDialog (null, "Data harus diisi");
            txt_total_bayar.requestFocus();
        }
        else if(txt_uang_kembali.getText().isEmpty()) {
            JOptionPane.showMessageDialog (null, "Data harus diisi"); 
            txt_uang_kembali.requestFocus();
        }
        else{
            if(edit==false){
                tiket.Simpan_Tiket(No_kursi, Nama_penumpang, Jumlah_beli, Uang_bayar, Total_bayar, Uang_kembali);
            }
            else{
                tiket.Edit_Tiket(No_kursi, Nama_penumpang, Jumlah_beli, Uang_bayar, Total_bayar, Uang_kembali);
            }
        }
        
        edit=false;
        tiket.tampilDatatiket_ka ();
        txt_no_kursi.setText("");
        txt_nama_penumpang.setText("");
        txt_jml_beli.setText("");
        txt_uang_bayar.setText("");
        txt_total_bayar.setText("");
        txt_uang_kembali.setText("");
        txt_no_kursi.requestFocus();
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
        boolean edit=false;
                edit=true;
        int row =tabel_tiket_ka.getSelectedRow();
        String no_kursi=tabel_tiket_ka.getValueAt(row, 0).toString();
        String nama_penumpang=tabel_tiket_ka.getValueAt(row, 1).toString();
        String jml_beli=tabel_tiket_ka.getValueAt(row, 2).toString();
        String uang_bayar=tabel_tiket_ka.getValueAt(row, 3).toString();
        String total_bayar=tabel_tiket_ka.getValueAt(row, 4).toString();
        String uang_kembali=tabel_tiket_ka.getValueAt(row, 5).toString();
        txt_no_kursi.setText(no_kursi);
        txt_nama_penumpang.setText(nama_penumpang);
        txt_jml_beli.setText(jml_beli);
        txt_uang_bayar.setText(uang_bayar);
        txt_total_bayar.setText(total_bayar);
        txt_uang_kembali.setText(uang_kembali);
        txt_no_kursi.setEditable(true);
        txt_nama_penumpang.requestFocus();
        txt_nama_penumpang.selectAll();
        
        txt_no_kursi.setEditable (true);
        txt_nama_penumpang.setEditable (true);
        btn_simpan.setEnabled(true);
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
        int konfirmasi=JOptionPane.showConfirmDialog (null, "Apakah data akan dihapus ?", "Konfirmasi", JOptionPane. YES_NO_OPTION);
        if (konfirmasi==JOptionPane.YES_OPTION) {
            int row=tabel_tiket_ka.getSelectedRow();
            String no_kursi=tabel_tiket_ka.getValueAt (row, 0).toString();
            tiket.Hapus_Tiket (no_kursi); 
            tiket.tampilDatatiket_ka ();
        }
    }//GEN-LAST:event_btn_hapusActionPerformed
boolean New=false;
    private void btn_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_newActionPerformed
        // TODO add your handling code here:
        txt_no_kursi.setText("");
        txt_nama_penumpang.setText("");
        txt_jml_beli.setText("");
        txt_uang_bayar.setText("");
        txt_total_bayar.setText("");
        txt_uang_kembali.setText("");
        btn_simpan.setEnabled(true);
        btn_new.setEnabled(false);
        New=true;
    }//GEN-LAST:event_btn_newActionPerformed

    private void btn_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_printActionPerformed
        // TODO add your handling code here:
        tiket.laporanTiket();
    }//GEN-LAST:event_btn_printActionPerformed

    private void btn_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kembaliActionPerformed
        // TODO add your handling code here:
        dispose();
        Menu_Utama menu=new Menu_Utama(null, rootPaneCheckingEnabled);
        menu.setVisible(true);
    }//GEN-LAST:event_btn_kembaliActionPerformed

    private void JurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JurusanActionPerformed
        // TODO add your handling code here:
        if (Jurusan.getSelectedItem().equals("Pilih Jurusan")) {
            buttonGroup1.clearSelection(); txt_Harga.setText ("");
        }
        else if (Jurusan.getSelectedItem().equals("Purwokerto - Solo")) {
            Vip=100000;
            Ekonomi=85000;
        }
        else if (Jurusan.getSelectedItem().equals("Purwokerto - Surabaya")) {
            Vip=180000;
            Ekonomi=100000;
        }
        else if (Jurusan.getSelectedItem().equals("Purwokerto - Semarang")) {
            Vip=150000;
            Ekonomi=95000;
        }
        else if (Jurusan.getSelectedItem().equals("Purwokerto - Bandung")) {
            Vip=140000;
            Ekonomi=90000;
        }
        else if (Jurusan.getSelectedItem().equals("Purwokerto - Jember")) {
            Vip=180000;
            Ekonomi=85000;
        }
    }//GEN-LAST:event_JurusanActionPerformed

    private void rb_VipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_VipActionPerformed
        // TODO add your handling code here:
        if(rb_Vip.isSelected());
        txt_Harga.setText(String.valueOf(Vip));
    }//GEN-LAST:event_rb_VipActionPerformed

    private void rb_EkonomiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_EkonomiActionPerformed
        // TODO add your handling code here:
        if(rb_Ekonomi.isSelected());
        txt_Harga.setText(String.valueOf(Ekonomi));
    }//GEN-LAST:event_rb_EkonomiActionPerformed

    private void txt_jml_beliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_jml_beliActionPerformed
        // TODO add your handling code here:
        Beli= Integer.parseInt(txt_jml_beli.getText ()); 
        Harga=Integer.parseInt(txt_total_bayar.getText()); 
        Total= Harga * Bayar; 
        txt_total_bayar.setText (String.valueOf (Total));
    }//GEN-LAST:event_txt_jml_beliActionPerformed

    private void txt_total_bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_total_bayarActionPerformed
        // TODO add your handling code here:
        Bayar= Integer.parseInt(txt_uang_bayar.getText ()); 
        Kembali=Integer.parseInt(txt_total_bayar.getText()); 
        Total= Harga - Kembali; 
        txt_uang_kembali.setText (String.valueOf (Total));
    }//GEN-LAST:event_txt_total_bayarActionPerformed

    private void txt_jml_beliKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_jml_beliKeyReleased
        // TODO add your handling code here:
        int a, b, c; 
        a=Integer.valueOf (txt_Harga.getText ()); 
        b=Integer.valueOf (txt_jml_beli.getText());
        c=a*b; 
        txt_total_bayar.setText (""+c);
    }//GEN-LAST:event_txt_jml_beliKeyReleased

    private void txt_uang_bayarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_uang_bayarKeyReleased
        // TODO add your handling code here:
        int a, b, c; 
        a=Integer.valueOf (txt_uang_bayar.getText ()); 
        b=Integer.valueOf (txt_total_bayar.getText());
        c=a - b; 
        txt_uang_kembali.setText (""+c);
    }//GEN-LAST:event_txt_uang_bayarKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Tiket_KA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Tiket_KA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Tiket_KA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Tiket_KA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Form_Tiket_KA dialog = new Form_Tiket_KA (new javax.swing.JFrame(),true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing (java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible (true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Jurusan;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_kembali;
    private javax.swing.JButton btn_new;
    private javax.swing.JButton btn_print;
    private javax.swing.JButton btn_simpan;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rb_Ekonomi;
    private javax.swing.JRadioButton rb_Vip;
    private javax.swing.JTable tabel_tiket_ka;
    private javax.swing.JTextField txt_Harga;
    private javax.swing.JTextField txt_jml_beli;
    private javax.swing.JTextField txt_nama_penumpang;
    private javax.swing.JTextField txt_no_kursi;
    private javax.swing.JTextField txt_total_bayar;
    private javax.swing.JTextField txt_uang_bayar;
    private javax.swing.JTextField txt_uang_kembali;
    // End of variables declaration//GEN-END:variables
}
